# Generated by Django 6.0.2 on 2026-05-08 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Fullname', models.CharField(max_length=50)),
                ('Phone_number', models.IntegerField(max_length=10)),
                ('Email', models.CharField()),
                ('Area', models.CharField()),
                ('Town', models.CharField()),
                ('Pin', models.IntegerField(max_length=6)),
                ('Password', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Workers_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Fullname', models.CharField(max_length=50)),
                ('Dob', models.DateField()),
                ('Gender', models.CharField()),
                ('Phone_number', models.IntegerField(max_length=10)),
                ('Email', models.CharField()),
                ('Photo', models.ImageField(blank=True, null=True, upload_to='photos/')),
                ('Town', models.CharField()),
                ('Pin', models.IntegerField(max_length=6)),
                ('Category', models.CharField()),
                ('Availability', models.CharField()),
                ('Password', models.CharField(max_length=128)),
            ],
        ),
    ]
