# Generated by Django 6.0.2 on 2026-05-10 05:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projectnearhelpapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Workers_details',
            new_name='Helper_details',
        ),
    ]
