# Generated by Django 6.0.2 on 2026-05-10 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectnearhelpapp', '0002_rename_workers_details_helper_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='helper_details',
            name='Area',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='helper_details',
            name='Town',
            field=models.CharField(max_length=100),
        ),
    ]
