# Generated by Django 6.0.2 on 2026-05-14 06:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectnearhelpapp', '0003_helper_details_area_alter_helper_details_town'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='client_details',
            name='Phone_number',
            field=models.IntegerField(),
        ),
        migrations.CreateModel(
            name='Job_postings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=80)),
                ('Category', models.CharField()),
                ('Description', models.TextField(max_length=500)),
                ('Photos', models.ImageField(blank=True, null=True, upload_to='job_photos/')),
                ('Budget', models.IntegerField()),
                ('Duration', models.CharField()),
                ('Urgency', models.CharField()),
                ('Area', models.CharField(max_length=100)),
                ('Town', models.CharField(max_length=100)),
                ('Pin', models.IntegerField(max_length=6)),
                ('Date_posted', models.DateTimeField(auto_now_add=True)),
                ('Client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
