# Generated by Django 6.0.2 on 2026-05-29 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectnearhelpapp', '0004_alter_client_details_phone_number_job_postings'),
    ]

    operations = [
        migrations.AddField(
            model_name='client_details',
            name='Preferred_contact_method',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='client_details',
            name='Preferred_language',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
