# Generated by Django 6.0.2 on 2026-05-30 07:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectnearhelpapp', '0005_client_details_preferred_contact_method_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='client_details',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='client_details', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='helper_details',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='helper_details', to=settings.AUTH_USER_MODEL),
        ),
    ]
