# Generated by Django 6.0.2 on 2026-06-01 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectnearhelpapp', '0006_client_details_user_helper_details_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client_details',
            name='Phone_number',
            field=models.CharField(),
        ),
        migrations.AlterField(
            model_name='client_details',
            name='Pin',
            field=models.IntegerField(),
        ),
    ]
