# Generated by Django 6.0.2 on 2026-06-01 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectnearhelpapp', '0007_alter_client_details_phone_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='job_postings',
            name='Status',
            field=models.CharField(default='open', max_length=20),
        ),
    ]
