# Generated by Django 6.0.2 on 2026-06-01 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectnearhelpapp', '0008_job_postings_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job_postings',
            name='Budget',
        ),
        migrations.AddField(
            model_name='job_postings',
            name='Budget_max',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='job_postings',
            name='Budget_min',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
