# Generated by Django 6.0.2 on 2026-06-01 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectnearhelpapp', '0009_remove_job_postings_budget_job_postings_budget_max_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='client_details',
            name='Photo',
            field=models.ImageField(blank=True, null=True, upload_to='photos/client_photos/'),
        ),
    ]
