# Generated by Django 6.0.2 on 2026-06-02 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectnearhelpapp', '0010_client_details_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='helper_details',
            name='Phone_number',
            field=models.CharField(),
        ),
        migrations.AlterField(
            model_name='helper_details',
            name='Pin',
            field=models.IntegerField(),
        ),
    ]
